from typing import Any, List

class PyEvent: ...

class StorageManager:
    def __init__(self, base_path: str) -> None: ...
    def save_event(self, event: PyEvent) -> None: ...

def download_sources(config_path: str) -> None: ...
def extract_competitions(data_dir: str) -> PyEvent: ...
def validate_extracted_competitions(event: PyEvent) -> bool: ...
def collect_dancing_data(config_path: str) -> List[PyEvent]: ...
