from typing import Any, List

class Event: ...
class Competition: ...
class Participant: ...
class Level: ...
class Style: ...
class AgeGroup: ...
class Dance: ...
class IdentityType: ...
class Judge: ...
class CommitteeMember: ...
class Officials: ...
class WDSFScore: ...
class Round: ...

class StorageManager:
    def __init__(self, base_path: str) -> None: ...
    def save_event(self, event: Event) -> None: ...

def download_sources(config_path: str) -> None: ...
def extract_competitions(data_dir: str) -> Event: ...
def validate_extracted_competitions(event: Event) -> bool: ...
def collect_dancing_data(config_path: str) -> List[Event]: ...
