from typing import Any, List

def download_sources(config_path: str) -> None: ...
def extract_competitions(data_dir: str) -> Any: ...
def validate_extracted_competitions(event: Any) -> bool: ...
def collect_dancing_data(config_path: str) -> List[Any]: ...
